- hosts: all
  become: true
  tasks:
     - name: create new deploymnet
       command: kubectl apply -f /ubuntu/Deployment.yml
     - name: create new serice
       command: kubectl apply  -f /ubuntu/Service.yml
