kind: Deployment
apiVersion: apps/v1
metadata:
    name: bidemi
spec:
    replicas: 2
    selector:      # tells the controller which pods to watch/belong to
    matchLabels: 
      app: mrdevops
   template:
      metadata:
        labels:
          app: mrdevops
      spec:
        containers:
          - name: bidemi
            image: bahme1980/pipeline_demo 
            image policy: Always
            port:
             - containerPort: 80 
