kind: Deployment
apiVersion: apps/v1
metadata:
    name: bidemi
spec:
    replicas: 2
    selector:   
    matchLabels: 
       app: bidemi
   template:
      metadata:
        labels:
          app: bidemi
      spec:
        containers:
          - name: bidemi
            image: bahme1980/pipeline_demo 
            image policy: Always
            port:
             - containerPort: 80
