kind: Deployment
apiVersion: apps/v1
metadata:
   name: bahmed1980
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
     matchLabels: 
      app: bidemi
   template:
      metadata:
        labels:
          app: bidemi
      spec:
       containers:
        - name: bahmed1980
          image: bahme1980/pipeline_demo:latest
          imagePullPolicy: Always
      imagePullSecrets:
           - name:bahmed1980/pipeline_demo-secret
          ports:
          - containerPort: 80
       
           
