kind: Service       
apiVersion: v1
metadata:
  name: bidemi
  labels:
    app: bidemi
spec:
  ports: 
    - port: 8080      
    targetPort: 80   
    nodePort: 31200
  selector:
    app: bidemi        
  type: LoadBalancer  
